version: '2'
services:
  emacs:
    build:
      context: .
    volumes:
      - $HOME:/mnt/workspace
      - data:/home/emacser/.emacs.d
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - development.env
volumes:
  data:
