version: '3'
services:
  emacs:
    image: "${COMPOSE_PROJECT_NAME}:${VERSION}"
    build:
      context: .
    network_mode: host
    volumes:
      - $HOME:/mnt/workspace
      - $HOME/.dbus:/mnt/workspace/.dbus
      - data:/home/emacser/.emacs.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - development.env
volumes:
  data:
