version: '3'
services:
  emacs:
    image: "${COMPOSE_PROJECT_NAME}:${VERSION}"
    build:
      context: .
    networks:
      - net
    volumes:
      - $HOME:/mnt/workspace
      - data:/home/emacser/.emacs.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - development.env
networks:
  net:
volumes:
  data:
