version: '2'
services:
  emacs:
    container_name: emacs
    networks:
      - net
    build:
      context: .
    volumes:
      - $HOME:/mnt/workspace
      - data:/home/emacser/.emacs.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - development.env
networks:
  net:
volumes:
  data:
