#!/usr/bin/env sh

cmd="$PROJECT_BUNDLE_CMD"

for i in "$@"; do
    case "$i" in
        *\'*)
            i=$(printf "%s" "$i")
            ;;
        *) : ;;
    esac
    cmd="$cmd $i"
done

cmd="$(printf "%s\\n" "'$cmd'")"

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$cmd"
