#!/usr/bin/env bash

docker run -d --rm \
       --cap-add=SYS_ADMIN \
	     --cpuset-cpus 0,1 \
	     --memory 1024mb \
       -e DISPLAY=$DISPLAY \
       -e $WORKSPACE/.dbus:/home/chromium/.dbus:ro \
       -e /var/run/pulse/.esd_auth:/home/chromium/.esd_auth:ro \
       -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
       -v $WORKSPACE/.Xauthority:/home/chromium/.Xauthority:ro \
       -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro \
	     -v $WORKSPACE/.cache/chromium:/home/chromium/.cache/chromium \
       -v $WORKSPACE/Downloads:/home/chromium/Downloads \
       --device /dev/snd \
       --device /dev/dri \
       --device /dev/video0 \
       -v /dev/shm:/dev/shm \
	     -v /usr/share/fonts:/usr/share/fonts:ro \
       --name chromium \
       afsmnghr/chromium:1.0.0-alpine --no-sandbox "$@"
