#!/usr/bin/env sh

cat /dev/null > /tmp/docker.out
args=$(printf "%s\t" "$@")
if [ "$args" != *"exec"* ]; then
  ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -T docker "$args" >> /tmp/docker.out
  cat /tmp/docker.out
else
  ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt docker "$args"
fi
