#!/usr/bin/env sh

cat /dev/null > /tmp/docker-machine.out

cmd='docker-machine'

for i in "$@"; do
    case "$i" in
        *\'*)
            i=$(printf "%s" "$i")
            ;;
        *=*)
            i=$(printf "%s" "$i" | sed -e "s/=\(.*\)/=\"\1\"/g")
            ;;
        *) : ;;
    esac
    cmd="$cmd $i"
done

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -T "$cmd" >> /tmp/docker-machine.out
cat /tmp/docker-machine.out
