#!/usr/bin/env sh

cat /dev/null > /tmp/docker-machine.out
args="$(printf %s\\n "$@" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/")"
ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -T docker-machine \
    "$args" >> /tmp/docker-machine.out
cat /tmp/docker-machine.out
