#!/bin/bash

if ! id "${UNAME}" >/dev/null 2>&1; then
  echo "${UNAME}:x:${UID}:${GID}:${UNAME},,,:${HOME}:${SHELL}" >> /etc/passwd
  echo "${UNAME}::17032:0:99999:7:::" >> /etc/shadow
fi

egrep -i "^${GNAME}" /etc/group;
if [ $? -ne 0 ]; then
  echo "${GNAME}:x:${GID}:${UNAME}" >> /etc/group
fi

if [ -d "${HOME}" ]; then
  home_owner="$(stat -c '%U' ${HOME})"
  if [ $(id -u ${UNAME}) -ne $(id -u ${home_owner}) ]; then
    chown "${UID}":"${GID}" -R ${HOME}
  fi
else
  mkdir -p "${HOME}"
  chown "${UID}":"${GID}" "${HOME}"
fi

mkdir -p "${WORKSPACE}"
chown "${UID}":"${GID}" "${WORKSPACE}"

VARS="HOME=$HOME TERM=$TERM WORKSPACE=$WORKSPACE ORG_FILES=$ORG_FILES"
VARS+=" REPOSITORY=$REPOSITORY BRANCH=$BRANCH HEAD_FORCE=$HEAD_FORCE"
VARS+=" HOST_USER=$HOST_USER HOST_IP=$HOST_IP HOST_PORT=$HOST_PORT"
VARS+=" DISPLAY=$DISPLAY WEB_BROWSER=$WEB_BROWSER"

su-exec "$UNAME" "$VARS $*"
