#!/usr/bin/env sh

# args :
#
#   --reports\=n --output-format\=text \
#   --msg-template\=\{path\}:\{line\}:\{column\}:\{C\}:\{symbol\}:\{msg\} \
#   --rcfile\=/local/path/.pylintrc /local/path/*.py

cmd="$PROJECT_PYLINT_CMD"

for i in "$@"; do
    case "$i" in
        *\'*)
            i=$(printf "%s" "$i")
            ;;
        *$PROJECT_LOCAL_PATH*)
            i=$(printf "%s" "$i" | \
                    sed -e "s|$PROJECT_LOCAL_PATH|$PROJECT_REMOTE_PATH|g")
            ;;
        *=*)
            i=$(printf "%s" "$i" | sed -e "s/=\(.*\)/=\"\1\"/g")
            ;;
        *) : ;;
    esac
    cmd="$cmd $i"
done

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$cmd" > /tmp/pylint.out

code="$?"

cat /tmp/pylint.out

exit "$code"
