#!/usr/bin/env sh

# INPUT:
#
#   --reports\=n --output-format\=text \
#   --msg-template\=\{path\}:\{line\}:\{column\}:\{C\}:\{symbol\}:\{msg\} \
#   --rcfile\=/local/path/.pylintrc /local/path/*.py
#
# OUTPUT:
#
#   server.py:34:12:R:no-else-return:Unnecessary "else" after "return"
#
# WORKS:
#   - python 3.7
#   - pylint==2.2.2

cmd="$PROJECT_PYLINT_CMD"

for i in "$@"; do
    case "$i" in
        *\\*)
            i=$(printf "%s" "$i")
            ;;
        *$PROJECT_LOCAL_PATH*)
            i=$(printf "%s" "$i" | \
                    sed -e "s|$PROJECT_LOCAL_PATH|$PROJECT_REMOTE_PATH|g")
            ;;
        *) : ;;
    esac
    cmd="$cmd $i"
done

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$cmd" > /tmp/pylint.out

if [ -n "$DEBUG" ]; then
    printf "DEBUG: You may test it with below command\n"
    printf "CMD: ssh "$HOST_USER"@"$HOST_IP" -p "$HOST_PORT" -tt %s\n\n" "$cmd"
fi

cat /tmp/pylint.out

exit 0
