#!/usr/bin/env sh

cat /dev/null > /tmp/rubocop.out
args="$(printf %s\\n "$@" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/")"

# args :
#
#   --display-cop-names --force-exclusion --format emacs --cache false \
#   --config /local/path/.robocop.yml --stdin /local/path/*.rb

args="$(echo "$args" | sed -e 's/--stdin//g' \
                           -e "s|$PROJECT_LOCAL_PATH|$PROJECT_REMOTE_PATH|g")"
echo "$args"

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$PROJECT_RUBOCOP_CMD" \
    "$args" >> /tmp/rubocop.out

result="$(grep "$PROJECT_REMOTE_PATH" /tmp/rubocop.out)"

if [ ! -z "$result" ]; then
    echo "$args" | sed -e "s|$PROJECT_LOCAL_PATH|$PROJECT_REMOTE_PATH|g"
    exit 0
else
    cat /tmp/rubocop.out
    exit 1
fi
