#!/usr/bin/env sh

initialize=$(cat <<EOF
(require 'org)
(find-file (concat user-emacs-directory "init.org"))
(org-babel-tangle)
(load-file (concat user-emacs-directory "init.el"))
(byte-compile-file (concat user-emacs-directory "init.el"))
EOF
)

ln -s "$WORKSPACE/.gitconfig" "$HOME/.gitconfig"
ln -s "$WORKSPACE/.ssh" "$HOME/.ssh"
ln -s "$WORKSPACE/.gnupg" "$HOME/.gnupg"

cd "$HOME/.emacs.d"

if [ ! -d "$HOME/.emacs.d/.git" ]; then
   git init
   git remote add origin "$REPOSITORY"
fi

(git fetch origin master || true)
git reset --hard origin/master

# first run literal configuration ...
if [ -f "$HOME/.emacs.d/init.org" ]; then
    emacs --batch --eval="$initialize"
fi

export ORG_PATH="$WORKSPACE/$ORG_FILES"
cd "$WORKSPACE"
emacs
