#!/usr/bin/env sh

cd "$HOME/.emacs.d"
ln -s "$HOME/.emacs.d/.eslintrc.yml" "$HOME/.eslintrc.yml"
ln -s "$WORKSPACE/.docker" "$HOME/.docker"
ln -s "$WORKSPACE/.git" "$HOME/.git"
ln -s "$WORKSPACE/.gitconfig" "$HOME/.gitconfig"
ln -s "$WORKSPACE/.ssh" "$HOME/.ssh"
ln -s "$WORKSPACE/.gnupg" "$HOME/.gnupg"
(git fetch origin master || true)
git reset --hard origin/master
(bundle check || bundle install --path "$HOME/.emacs.d/bundle" || true)
(npm install || true) && export PATH="$(npm bin):$PATH"
export ORG_PATH="$WORKSPACE/$ORG_FILES"
cd "$WORKSPACE"
emacs
