#!/usr/bin/env sh

set -x

export "$(cat "$WORKSPACE"/.dockemacs)"

ln -s "$WORKSPACE/.gitconfig" "$HOME/.gitconfig"
ln -s "$WORKSPACE/.ssh" "$HOME/.ssh"
ln -s "$WORKSPACE/.gnupg" "$HOME/.gnupg"

cd "$HOME/.emacs.d" || exit

if [ ! -d "$HOME/.emacs.d/.git" ]; then
   git init
   git remote add origin "$REPOSITORY"
   git checkout --track "origin/$BRANCH"
fi

git fetch origin "$BRANCH" || true

echo 'after fetch'

if [ -n "$HEAD_FORCE" ]; then
    git reset --hard "origin/$BRANCH"
fi

echo 'after reset'

if [ ! -f "$HOME/.emacs.d/.head" ]; then
    touch .head
fi

echo 'after head'

previous_commit="$(cat "$HOME/.emacs.d/.head")"
current_commit="$(git rev-parse HEAD)"
retangle="$(git status --porcelain | grep init.org)"

echo 'before retangle'

if [ -f "$HOME/.emacs.d/init.org" ] && (
       [ ! -f "$HOME/.emacs.d/init.el" ] ||
           ([ "$previous_commit" != "$current_commit" ] &&
                [ -n "$retangle" ])); then
    tangle
    echo "$current_commit" > .head
fi

echo 'after retangle'

export ORG_PATH="$WORKSPACE/$ORG_FILES"
cd "$WORKSPACE" || exit
emacs
