#!/usr/bin/env sh
":"; exec emacs --quick --script "$0" "$@" # -*-emacs-lisp-*-

(require 'org)
(setq gc-cons-threshold most-positive-fixnum)
(find-file (concat user-emacs-directory "init.org"))
(org-babel-tangle)
(load-file (concat user-emacs-directory "init.el"))
(byte-compile-file (concat user-emacs-directory "init.el"))
(if (file-exists-p (concat user-emacs-directory "early-init.el"))
  (byte-compile-file (concat user-emacs-directory "early-init.el")))
(setq gc-cons-threshold 800000)
