#!/usr/bin/env sh

# args :
#
#   --format json --config /local/path/tslint.json \
#   --project /local/path/tsconfig.json /local/path/flycheck_*.ts

cat /dev/null > /tmp/tslint.out

cmd="$PROJECT_TSLINT_CMD"

for i in "$@"; do
    case "$i" in
        *\'*)
            i=$(printf "%s" "$i")
            ;;
        *flycheck_*)
            i=$(printf "%s" "$i" | sed -e 's/flycheck_//g')
            ;;
        $PROJECT_LOCAL_PATH*)
            i=$(printf "%s" "$i" | \
                    sed -e "s|$PROJECT_LOCAL_PATH|$PROJECT_REMOTE_PATH|g")
            ;;
        *) : ;;
    esac
    cmd="$cmd $i"
done

cmd="$(printf "%s\\n" "$cmd" | sed -e "s/tslint'/tslint/g")"

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$cmd'" >> /tmp/tslint.out

code="$?"

cat /tmp/tslint.out | sed -e "s|$PROJECT_REMOTE_PATH|$PROJECT_LOCAL_PATH|g"
exit "$code"
